Adjusts package version extraction
Updates the workflow to correctly extract the package
version based on the package being built.

This ensures that the correct version information is
used for each package during the release process.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -190,7 +190,19 @@ jobs:
 
       - name: set the package version
         run: |
-          export VERSION=$(cat ./__about__.py)
+          PACKAGE_DIR=""
+          if [ ${{ matrix.package }} = "nextmv" ]; then
+            PACKAGE_DIR="nextmv"
+          elif [ ${{ matrix.package }} = "nextmv-gurobipy" ]; then
+            PACKAGE_DIR="nextmv-gurobipy"
+          elif [ ${{ matrix.package }} = "nextmv-scikit-learn" ]; then
+            PACKAGE_DIR="nextmv-sklearn"
+          else
+            echo "Invalid package"
+            exit 1
+          fi
+
+          export VERSION=$(cat ./$PACKAGE_DIR/__about__.py)
           echo "VERSION=${{ env.VERSION }}" >> $GITHUB_ENV
 
           export PACKAGE_VERSION="${{ matrix.package }}-$VERSION"
